Repository Preonboarding-Nest/blog-api-service, pull requests merged in 2022-09, with the labels that each got.

#10 fix: find user / delete user 기능 요구사항 미반영 해결
  backend/src/users/users.service.ts
Labels: fix

#8 Feature/issue 3-2
  backend/src/app.module.ts
  backend/src/posts/dto/create-post.dto.ts
  backend/src/posts/dto/create-postCategory.dto.ts
  backend/src/posts/dto/find-post.dto.ts
  backend/src/posts/dto/update-post.dto.ts
  backend/src/posts/dto/update-postCategory.dto.ts
  backend/src/posts/entities/post-category.entity.ts
  backend/src/posts/entities/post.entity.ts
  backend/src/posts/posts-category.controller.ts
  backend/src/posts/posts-category.service.ts
  backend/src/posts/posts.controller.spec.ts
  backend/src/posts/posts.controller.ts
  backend/src/posts/posts.module.ts
  backend/src/posts/posts.service.spec.ts
  backend/src/posts/posts.service.ts
Labels: feat

#9 JSend Format (Response Format)적용
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/commons/interfaces/response.interface.ts
  backend/src/filters/all-exception.filter.ts
  backend/src/interceptors/response.interceptor.ts
Labels: feat

#7 Auth API
  backend/docker-compose.yml
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/index.ts
  backend/src/auth/dto/login.dto.ts
  backend/src/auth/strategy/index.ts
  backend/src/auth/strategy/jwt.refresh.strategy.ts
  backend/src/auth/strategy/jwt.strategy.ts
  backend/src/auth/types/index.ts
  backend/src/auth/types/jwtPayload.type.ts
  backend/src/auth/types/tokens.type.ts
  backend/src/commons/decorators/get.current-userId.decorator.ts
  backend/src/commons/decorators/index.ts
  backend/src/main.ts
  backend/src/redis/redis.module.ts
  backend/src/redis/redis.service.spec.ts
  backend/src/redis/redis.service.ts
Labels: feat

#11 JSend Format 적용 관련 추가 수정
  backend/src/filters/all-exception.filter.ts
Labels: fix

#12 Posts API
  backend/.eslintrc.js
  backend/src/posts/dto/find-post.dto.ts
  backend/src/posts/entities/post.entity.ts
  backend/src/posts/posts.controller.ts
  backend/src/posts/posts.service.ts
  backend/src/users/entities/user.entity.ts
Labels: feat

#20 Staticstics 기능 수정 작업
  backend/package.json
  backend/src/commons/constants.ts
  backend/src/commons/enums/commons.enums.ts
  backend/src/statistics/entities/statistic.entity.ts
  backend/src/statistics/events/statistics-save.event.ts
  backend/src/statistics/listeners/statistics-save.listener.ts
Labels: feat, fix

#21 Posts API 인가 처리 추가 구현
  backend/src/commons/enums/commons.enums.ts
  backend/src/posts/dto/create-post.dto.ts
  backend/src/posts/entities/post-category.entity.ts
  backend/src/posts/entities/post.entity.ts
  backend/src/posts/posts.controller.ts
  backend/src/posts/posts.service.ts
Labels: feat

#23 Uses service Unit 테스트
  backend/src/users/users.service.spec.ts
Labels: test

#25 Posts Service Unit 테스트
  backend/src/posts/dto/create-post.dto.ts
  backend/src/posts/posts.service.spec.ts
Labels: test

#26 Post Category Service Unit 테스트
  backend/src/posts/posts-category.service.spec.ts
Labels: test

#30 User API response serialization 구현
  backend/src/interceptors/serialize.interceptor.ts
  backend/src/main.ts
  backend/src/users/dto/create-user.dto.ts
  backend/src/users/users.controller.ts
Labels: feat

#33 Users 통계를 위한 EventEmitter 적용
  backend/src/users/users.controller.ts
Labels: feat

#32 게시글 통계용 emit 코드 추가
  backend/src/posts/posts.controller.ts
  backend/src/posts/posts.service.ts
Labels: feat

#37 Statistics 기본 기능 추가 수정
  backend/src/commons/constants.ts
  backend/src/commons/enums/commons.enums.ts
  backend/src/statistics/dto/find-statistics.dto.ts
  backend/src/statistics/statistics.controller.ts
  backend/src/statistics/statistics.module.ts
  backend/src/statistics/statistics.service.ts
  backend/src/users/users.module.ts
Labels: feat

#35 User resource 주석 작성
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: chore

#27 Auth Test Case 추가, docker compose network 추가 #14 #17
  README.md
  backend/docker-compose.yml
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/redis/redis.service.spec.ts
Labels: feat, test

#40 posts-category 통계를 위한 event emitter 적용
  backend/src/posts/posts-category.controller.ts
  backend/src/posts/posts-category.service.ts
Labels: chore, feat, fix

#41 posts-category 주석 적용
  backend/src/posts/posts-category.service.ts
Labels: chore

#42 통계 조회 기능 추가
  backend/src/commons/enums/commons.enums.ts
  backend/src/statistics/dto/find-statistics.dto.ts
  backend/src/statistics/statistics.controller.ts
  backend/src/statistics/statistics.service.ts
Labels: feat, fix

#44 Statistics service 주석 추가
  backend/src/statistics/statistics.service.ts
Labels: chore

#45 통계 기능 추가로 인한 develop -> main merge
  backend/src/commons/enums/commons.enums.ts
  backend/src/statistics/dto/find-statistics.dto.ts
  backend/src/statistics/statistics.controller.ts
  backend/src/statistics/statistics.service.ts
Labels: chore, feat, fix
